#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

assert_file_exists() {
  local path="$1"
  [ -f "$path" ] || fail "Expected file to exist: $path"
}

assert_path_missing() {
  local path="$1"
  [ ! -e "$path" ] || fail "Expected path to be absent: $path"
}

assert_not_symlink() {
  local path="$1"
  [ ! -L "$path" ] || fail "Expected regular file, found symlink: $path"
}

assert_file_contains() {
  local path="$1" needle="$2"
  grep -Fq -- "$needle" "$path" || fail "Expected '$needle' in $path"
}

TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/codex-install.XXXXXX")"
trap 'rm -rf "$TMP_ROOT"' EXIT

# --- Basic install: a single concatenated AGENTS.md, no instructions dir ----
TMP_HOME="$TMP_ROOT/basic"
mkdir -p "$TMP_HOME/.codex"

HOME="$TMP_HOME" "$REPO_DIR/setup.sh" --agent codex --yes >/dev/null

AGENTS_FILE="$TMP_HOME/.codex/AGENTS.md"
assert_file_exists "$AGENTS_FILE"
assert_not_symlink "$AGENTS_FILE"
# Managed marker on line 1 so the installer can own the file.
[ "$(head -1 "$AGENTS_FILE")" = "<!-- ai-instructions:managed -->" ] \
  || fail "Expected managed marker on line 1 of $AGENTS_FILE"
# Concatenated instruction sources are present.
assert_file_contains "$AGENTS_FILE" "<!-- source: core.md -->"
assert_file_contains "$AGENTS_FILE" "# Core Instructions"
# Skills use Codex's standard user-level Agent Skills directory.
CODEX_SKILL="$TMP_HOME/.agents/skills/write-pr-description/SKILL.md"
assert_file_exists "$CODEX_SKILL"
assert_file_contains "$CODEX_SKILL" "name: write-pr-description"
# No legacy per-file instructions directory is created.
assert_path_missing "$TMP_HOME/.codex/instructions"

# --- Idempotent check / list / re-install ----------------------------------
HOME="$TMP_HOME" "$REPO_DIR/setup.sh" check --agent codex --yes >/dev/null
HOME="$TMP_HOME" "$REPO_DIR/setup.sh" list --agent codex --yes >"$TMP_HOME/list.log"
assert_file_contains "$TMP_HOME/list.log" "AGENTS.md (concatenated)"

HOME="$TMP_HOME" "$REPO_DIR/setup.sh" --agent codex --yes >"$TMP_HOME/reinstall.log"
assert_file_contains "$TMP_HOME/reinstall.log" "Already up to date"

# --- Out-of-date check fails so it can be used in automation ----------------
printf '<!-- ai-instructions:managed -->\n# stale\n' > "$AGENTS_FILE"
if HOME="$TMP_HOME" "$REPO_DIR/setup.sh" check --agent codex --yes >"$TMP_HOME/stale-check.log" 2>&1; then
  fail "Expected check to fail when managed Codex instructions are out of date"
fi
assert_file_contains "$TMP_HOME/stale-check.log" "out of date"
# update brings it back in sync.
HOME="$TMP_HOME" "$REPO_DIR/setup.sh" update --agent codex --yes >/dev/null
assert_file_contains "$AGENTS_FILE" "# Core Instructions"

# --- Remove only deletes the managed file ----------------------------------
HOME="$TMP_HOME" "$REPO_DIR/setup.sh" remove --agent codex --yes >/dev/null
assert_path_missing "$AGENTS_FILE"

# --- Refuses to clobber a user-maintained AGENTS.md ------------------------
TMP_USER="$TMP_ROOT/user"
mkdir -p "$TMP_USER/.codex"
printf '# my personal agents file\n' > "$TMP_USER/.codex/AGENTS.md"

HOME="$TMP_USER" "$REPO_DIR/setup.sh" --agent codex --yes >"$TMP_USER/install.log" 2>&1
assert_file_contains "$TMP_USER/install.log" "was not generated by this script"
assert_file_contains "$TMP_USER/.codex/AGENTS.md" "# my personal agents file"
# A user-owned file must not be removed either.
HOME="$TMP_USER" "$REPO_DIR/setup.sh" remove --agent codex --yes >/dev/null
assert_file_exists "$TMP_USER/.codex/AGENTS.md"

# A conflicting AGENTS.md symlink is preserved and reported on remove.
printf '# external agents\n' > "$TMP_USER/external-agents.md"
ln -sf "$TMP_USER/external-agents.md" "$TMP_USER/.codex/AGENTS.md"
HOME="$TMP_USER" "$REPO_DIR/setup.sh" remove --agent codex --yes >"$TMP_USER/remove-link.log" 2>&1
assert_file_contains "$TMP_USER/remove-link.log" "was not generated by this script"
[ -L "$TMP_USER/.codex/AGENTS.md" ] || fail "Expected user AGENTS.md symlink to be preserved on remove"

# --- Migrates away from the legacy per-file layout --------------------------
TMP_LEGACY="$TMP_ROOT/legacy"
mkdir -p "$TMP_LEGACY/.codex/instructions"
# A managed copy and a symlink into the repo are both ours and should go.
printf '<!-- ai-instructions:managed -->\n# old\n' > "$TMP_LEGACY/.codex/instructions/coding-principles.md"
ln -s "$REPO_DIR/instructions/core.md" "$TMP_LEGACY/.codex/instructions/security.md"
# A user-authored file in the legacy dir must be preserved.
printf '# keep me\n' > "$TMP_LEGACY/.codex/instructions/my-notes.md"
# A user symlink pointing outside the repo must also be preserved.
printf '# external\n' > "$TMP_LEGACY/external.md"
ln -s "$TMP_LEGACY/external.md" "$TMP_LEGACY/.codex/instructions/user-link.md"
# A user symlink targeting a repo file outside instructions/ (e.g. a skill)
# was never installed by this script and must be preserved.
ln -s "$REPO_DIR/skills/refactor/SKILL.md" "$TMP_LEGACY/.codex/instructions/user-skill-link.md"

HOME="$TMP_LEGACY" "$REPO_DIR/setup.sh" --agent codex --yes >"$TMP_LEGACY/install.log" 2>&1
assert_file_contains "$TMP_LEGACY/install.log" "legacy Codex instructions"
assert_path_missing "$TMP_LEGACY/.codex/instructions/coding-principles.md"
assert_path_missing "$TMP_LEGACY/.codex/instructions/security.md"
assert_file_exists "$TMP_LEGACY/.codex/instructions/my-notes.md"
[ -L "$TMP_LEGACY/.codex/instructions/user-link.md" ] || fail "Expected user symlink to be preserved"
[ -L "$TMP_LEGACY/.codex/instructions/user-skill-link.md" ] || fail "Expected repo-skill symlink to be preserved"
assert_file_exists "$TMP_LEGACY/.codex/AGENTS.md"

# --- Leaves a broken/foreign AGENTS.md symlink alone (does not clobber) ------
# A dangling symlink slips past an `-e` conflict check (it follows the link),
# but we must not write through it (would error under set -e) nor delete the
# user's link. Expect a skip + warning, with the symlink preserved.
TMP_BROKEN="$TMP_ROOT/broken"
mkdir -p "$TMP_BROKEN/.codex"
ln -s "$TMP_BROKEN/.codex/does-not-exist.md" "$TMP_BROKEN/.codex/AGENTS.md"
[ -L "$TMP_BROKEN/.codex/AGENTS.md" ] || fail "Expected a broken symlink seed"

HOME="$TMP_BROKEN" "$REPO_DIR/setup.sh" --agent codex --yes >"$TMP_BROKEN/install.log" 2>&1
assert_file_contains "$TMP_BROKEN/install.log" "was not generated by this script"
[ -L "$TMP_BROKEN/.codex/AGENTS.md" ] || fail "Expected broken symlink to be preserved"
assert_path_missing "$TMP_BROKEN/.codex/does-not-exist.md"
if HOME="$TMP_BROKEN" "$REPO_DIR/setup.sh" check --agent codex --yes >"$TMP_BROKEN/check.log" 2>&1; then
  fail "Expected check to fail for a conflicting user-owned AGENTS.md symlink"
fi
assert_file_contains "$TMP_BROKEN/check.log" "was not generated by this script"

# --- Dry run makes no changes ----------------------------------------------
TMP_DRY="$TMP_ROOT/dry"
mkdir -p "$TMP_DRY/.codex"
HOME="$TMP_DRY" "$REPO_DIR/setup.sh" --agent codex --dry-run --yes >"$TMP_DRY/dry.log" 2>&1
assert_file_contains "$TMP_DRY/dry.log" "dry-run"
assert_path_missing "$TMP_DRY/.codex/AGENTS.md"

# --- --only skills installs skills without creating global instructions -----
TMP_ONLY="$TMP_ROOT/only"
mkdir -p "$TMP_ONLY/.codex"
HOME="$TMP_ONLY" "$REPO_DIR/setup.sh" --agent codex --only skills --yes >/dev/null
assert_path_missing "$TMP_ONLY/.codex/AGENTS.md"
assert_file_exists "$TMP_ONLY/.agents/skills/refactor/SKILL.md"

# --- check on a clean home reports missing managed artifacts ----------------
TMP_CLEAN="$TMP_ROOT/clean"
mkdir -p "$TMP_CLEAN/.codex"
if HOME="$TMP_CLEAN" "$REPO_DIR/setup.sh" check --agent codex --yes >/dev/null 2>&1; then
  fail "Expected check to fail when managed Codex artifacts are missing"
fi

# --- --copy mode still produces a managed file (no symlink) -----------------
TMP_COPY="$TMP_ROOT/copy"
mkdir -p "$TMP_COPY/.codex"
HOME="$TMP_COPY" "$REPO_DIR/setup.sh" --agent codex --copy --yes >/dev/null
assert_file_exists "$TMP_COPY/.codex/AGENTS.md"
assert_not_symlink "$TMP_COPY/.codex/AGENTS.md"

echo "codex installer regression test passed"
