#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

assert_file_exists() {
  local path="$1"
  [ -f "$path" ] || fail "Expected file to exist: $path"
}

assert_path_missing() {
  local path="$1"
  [ ! -e "$path" ] || fail "Expected path to be absent: $path"
}

assert_not_symlink() {
  local path="$1"
  [ ! -L "$path" ] || fail "Expected regular file, found symlink: $path"
}

assert_file_contains() {
  local path="$1" needle="$2"
  grep -Fq "$needle" "$path" || fail "Expected '$needle' in $path"
}

TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/codex-install.XXXXXX")"
trap 'rm -rf "$TMP_ROOT"' EXIT

# --- Basic install: a single concatenated AGENTS.md, no instructions dir ----
TMP_HOME="$TMP_ROOT/basic"
mkdir -p "$TMP_HOME/.codex"

HOME="$TMP_HOME" "$REPO_DIR/setup.sh" --agent codex --yes >/dev/null

AGENTS_FILE="$TMP_HOME/.codex/AGENTS.md"
assert_file_exists "$AGENTS_FILE"
assert_not_symlink "$AGENTS_FILE"
# Managed marker on line 1 so the installer can own the file.
[ "$(head -1 "$AGENTS_FILE")" = "<!-- ai-instructions:managed -->" ] \
  || fail "Expected managed marker on line 1 of $AGENTS_FILE"
# Concatenated instruction sources are present.
assert_file_contains "$AGENTS_FILE" "<!-- source: coding-principles.md -->"
assert_file_contains "$AGENTS_FILE" "# Accessibility Standards"
# Routing table is inlined and references the source skill files (no per-agent
# skills install exists for Codex).
assert_file_contains "$AGENTS_FILE" "# Workflow Routing"
assert_file_contains "$AGENTS_FILE" "$REPO_DIR/skills/write-pr-description.md"
# No legacy per-file instructions directory is created.
assert_path_missing "$TMP_HOME/.codex/instructions"

# --- Idempotent check / list / re-install ----------------------------------
HOME="$TMP_HOME" "$REPO_DIR/setup.sh" check --agent codex --yes >/dev/null
HOME="$TMP_HOME" "$REPO_DIR/setup.sh" list --agent codex --yes >"$TMP_HOME/list.log"
assert_file_contains "$TMP_HOME/list.log" "$AGENTS_FILE (concatenated)"

HOME="$TMP_HOME" "$REPO_DIR/setup.sh" --agent codex --yes >"$TMP_HOME/reinstall.log"
assert_file_contains "$TMP_HOME/reinstall.log" "Already up to date"

# --- Out-of-date check fails-soft (reported as conflict, not OK) ------------
printf '<!-- ai-instructions:managed -->\n# stale\n' > "$AGENTS_FILE"
HOME="$TMP_HOME" "$REPO_DIR/setup.sh" check --agent codex --yes >"$TMP_HOME/stale-check.log" 2>&1
assert_file_contains "$TMP_HOME/stale-check.log" "out of date"
# update brings it back in sync.
HOME="$TMP_HOME" "$REPO_DIR/setup.sh" update --agent codex --yes >/dev/null
assert_file_contains "$AGENTS_FILE" "# Workflow Routing"

# --- Remove only deletes the managed file ----------------------------------
HOME="$TMP_HOME" "$REPO_DIR/setup.sh" remove --agent codex --yes >/dev/null
assert_path_missing "$AGENTS_FILE"

# --- Refuses to clobber a user-maintained AGENTS.md ------------------------
TMP_USER="$TMP_ROOT/user"
mkdir -p "$TMP_USER/.codex"
printf '# my personal agents file\n' > "$TMP_USER/.codex/AGENTS.md"

HOME="$TMP_USER" "$REPO_DIR/setup.sh" --agent codex --yes >"$TMP_USER/install.log" 2>&1
assert_file_contains "$TMP_USER/install.log" "was not generated by this script"
assert_file_contains "$TMP_USER/.codex/AGENTS.md" "# my personal agents file"
# A user-owned file must not be removed either.
HOME="$TMP_USER" "$REPO_DIR/setup.sh" remove --agent codex --yes >/dev/null
assert_file_exists "$TMP_USER/.codex/AGENTS.md"

# --- Migrates away from the legacy per-file layout --------------------------
TMP_LEGACY="$TMP_ROOT/legacy"
mkdir -p "$TMP_LEGACY/.codex/instructions"
# A managed copy and a symlink into the repo are both ours and should go.
printf '<!-- ai-instructions:managed -->\n# old\n' > "$TMP_LEGACY/.codex/instructions/coding-principles.md"
ln -s "$REPO_DIR/instructions/security.md" "$TMP_LEGACY/.codex/instructions/security.md"
# A user-authored file in the legacy dir must be preserved.
printf '# keep me\n' > "$TMP_LEGACY/.codex/instructions/my-notes.md"

HOME="$TMP_LEGACY" "$REPO_DIR/setup.sh" --agent codex --yes >"$TMP_LEGACY/install.log" 2>&1
assert_file_contains "$TMP_LEGACY/install.log" "legacy Codex instructions"
assert_path_missing "$TMP_LEGACY/.codex/instructions/coding-principles.md"
assert_path_missing "$TMP_LEGACY/.codex/instructions/security.md"
assert_file_exists "$TMP_LEGACY/.codex/instructions/my-notes.md"
assert_file_exists "$TMP_LEGACY/.codex/AGENTS.md"

# --- --copy mode still produces a managed file (no symlink) -----------------
TMP_COPY="$TMP_ROOT/copy"
mkdir -p "$TMP_COPY/.codex"
HOME="$TMP_COPY" "$REPO_DIR/setup.sh" --agent codex --copy --yes >/dev/null
assert_file_exists "$TMP_COPY/.codex/AGENTS.md"
assert_not_symlink "$TMP_COPY/.codex/AGENTS.md"

echo "codex installer regression test passed"
