import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

export const MANAGED_MARKER = '<!-- ai-instructions:managed -->';
export const TOML_MANAGED_MARKER = '# ai-instructions:managed';
// This historical string is an ownership sentinel; changing it requires a migration.
export const COPILOT_EXPORT_MARKER = '<!-- Auto-generated by ai-instructions/setup.sh --copilot-concat -->';

function ensureTrailingNewline( value ) {
	return value.endsWith( '\n' ) ? value : `${ value }\n`;
}

export function normalizeMarkdown( value ) {
	return value.replace( /\r\n?/g, '\n' );
}

function parseFrontmatterScalar( value, key, source ) {
	value = value.trim();
	if ( [ '>', '|' ].includes( value[ 0 ] ) ) {
		throw new Error( `${ source }: frontmatter field '${ key }' must use a single-line scalar.` );
	}

	if ( value.startsWith( "'" ) ) {
		if ( value.length < 2 || ! value.endsWith( "'" ) ) {
			throw new Error( `${ source }: frontmatter field '${ key }' has an unterminated quoted scalar.` );
		}
		const inner = value.slice( 1, -1 );
		let decoded = '';
		for ( let index = 0; index < inner.length; index++ ) {
			if ( inner[ index ] !== "'" ) {
				decoded += inner[ index ];
				continue;
			}
			if ( inner[ index + 1 ] !== "'" ) {
				throw new Error( `${ source }: frontmatter field '${ key }' has an invalid single-quoted scalar.` );
			}
			decoded += "'";
			index++;
		}
		value = decoded;
	} else if ( value.startsWith( '"' ) ) {
		if ( value.length < 2 || ! value.endsWith( '"' ) ) {
			throw new Error( `${ source }: frontmatter field '${ key }' has an unterminated quoted scalar.` );
		}
		value = value.slice( 1, -1 );
		if ( value.includes( '\\' ) || value.includes( '"' ) ) {
			throw new Error( `${ source }: frontmatter field '${ key }' uses unsupported quoted escapes.` );
		}
	} else {
		value = value.replace( /\s+#.*$/, '' ).trim();
	}

	if ( value === '' ) {
		throw new Error( `${ source }: frontmatter field '${ key }' must not be empty.` );
	}
	return value;
}

export function parseFrontmatter( content, source = 'Markdown file' ) {
	content = normalizeMarkdown( content );
	if ( ! content.startsWith( '---\n' ) ) {
		throw new Error( `${ source }: YAML frontmatter must be the first content.` );
	}
	const closing = content.indexOf( '\n---\n', 4 );
	if ( closing < 0 ) {
		throw new Error( `${ source }: YAML frontmatter is not closed.` );
	}

	const values = {};
	let rootIndentation;
	for ( const line of content.slice( 4, closing ).split( '\n' ) ) {
		if ( /^\s*(?:#.*)?$/.test( line ) ) {
			continue;
		}
		const indentation = line.match( /^\s*/ )[ 0 ].length;
		rootIndentation ??= indentation;
		if ( indentation !== rootIndentation ) {
			continue;
		}
		const match = line.match( /^\s*([a-zA-Z][a-zA-Z0-9-]*)\s*:\s*(.*)$/ );
		if ( match && values[ match[ 1 ] ] === undefined ) {
			values[ match[ 1 ] ] = parseFrontmatterScalar( match[ 2 ], match[ 1 ], source );
		}
	}
	for ( const key of [ 'name', 'description' ] ) {
		if ( ! values[ key ] ) {
			throw new Error( `${ source }: missing required frontmatter field '${ key }'.` );
		}
	}

	return {
		...values,
		body: content.slice( closing + 5 ).replace( /^\n/, '' ),
	};
}

export function managedMarkdown( content ) {
	content = normalizeMarkdown( content );
	const normalized = ensureTrailingNewline( content );
	if ( normalized.startsWith( '---\n' ) ) {
		return `${ normalized }${ MANAGED_MARKER }\n`;
	}
	return `${ MANAGED_MARKER }\n${ normalized }`;
}

export function cursorRule( content, source ) {
	content = normalizeMarkdown( content );
	const heading = content.match( /^#\s+(.+)$/m )?.[ 1 ] ?? path.basename( source, path.extname( source ) ).replaceAll( '-', ' ' );
	const description = heading.replaceAll( "'", "''" );
	return `---\ndescription: '${ description }'\nalwaysApply: true\n---\n${ MANAGED_MARKER }\n${ ensureTrailingNewline( content ) }`;
}

function tomlString( value ) {
	return value.replaceAll( '\\', '\\\\' ).replaceAll( '"', '\\"' );
}

export function codexAgent( content, source ) {
	content = normalizeMarkdown( content );
	const { name, description, body } = parseFrontmatter( content, source );
	return `${ TOML_MANAGED_MARKER }\nname = "${ tomlString( name ) }"\ndescription = "${ tomlString( description ) }"\ndeveloper_instructions = """\n${ tomlString( ensureTrailingNewline( body ) ) }"""\n`;
}

export async function concatInstructions( instructionsDir ) {
	const names = ( await readdir( instructionsDir ) )
		.filter( ( name ) => name.endsWith( '.md' ) )
		.sort();
	const sections = [];
	for ( const name of names ) {
		const content = ensureTrailingNewline( normalizeMarkdown( await readFile( path.join( instructionsDir, name ), 'utf8' ) ) );
		sections.push( `<!-- source: ${ name } -->\n\n${ content }\n---\n` );
	}
	return `${ sections.join( '\n' ) }\n`;
}

export function concatenatedInstructions( content ) {
	return `${ MANAGED_MARKER }\n${ content }`;
}

export function copilotProjectExport( content ) {
	return `${ COPILOT_EXPORT_MARKER }\n<!-- Do not edit manually. Re-run setup.sh to update. -->\n\n${ content }`;
}
