import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

export const MANAGED_MARKER = '<!-- ai-instructions:managed -->';
export const TOML_MANAGED_MARKER = '# ai-instructions:managed';
export const COPILOT_EXPORT_MARKER = '<!-- Auto-generated by ai-instructions/setup.sh --copilot-concat -->';

function ensureTrailingNewline( value ) {
	return value.endsWith( '\n' ) ? value : `${ value }\n`;
}

export function normalizeMarkdown( value ) {
	return value.replace( /\r\n?/g, '\n' );
}

export function parseFrontmatter( content, source = 'Markdown file' ) {
	content = normalizeMarkdown( content );
	if ( ! content.startsWith( '---\n' ) ) {
		throw new Error( `${ source }: YAML frontmatter must be the first content.` );
	}
	const closing = content.indexOf( '\n---\n', 4 );
	if ( closing < 0 ) {
		throw new Error( `${ source }: YAML frontmatter is not closed.` );
	}

	const values = {};
	for ( const line of content.slice( 4, closing ).split( '\n' ) ) {
		const match = line.match( /^([a-zA-Z][a-zA-Z0-9-]*):\s*(.+)$/ );
		if ( match ) {
			values[ match[ 1 ] ] = match[ 2 ].replace( /^(?:'([^']*)'|"([^"]*)")$/, '$1$2' );
		}
	}
	for ( const key of [ 'name', 'description' ] ) {
		if ( ! values[ key ] ) {
			throw new Error( `${ source }: frontmatter requires ${ key }.` );
		}
	}

	return {
		...values,
		body: content.slice( closing + 5 ).replace( /^\n/, '' ),
	};
}

export function managedMarkdown( content ) {
	content = normalizeMarkdown( content );
	const normalized = ensureTrailingNewline( content );
	if ( normalized.startsWith( '---\n' ) ) {
		return `${ normalized }${ MANAGED_MARKER }\n`;
	}
	return `${ MANAGED_MARKER }\n${ normalized }`;
}

export function cursorRule( content, source ) {
	content = normalizeMarkdown( content );
	const heading = content.match( /^#\s+(.+)$/m )?.[ 1 ] ?? path.basename( source, path.extname( source ) ).replaceAll( '-', ' ' );
	const description = heading.replaceAll( "'", "''" );
	return `---\ndescription: '${ description }'\nalwaysApply: true\n---\n${ MANAGED_MARKER }\n${ ensureTrailingNewline( content ) }`;
}

function tomlString( value ) {
	return value.replaceAll( '\\', '\\\\' ).replaceAll( '"', '\\"' );
}

export function codexAgent( content, source ) {
	content = normalizeMarkdown( content );
	const { name, description, body } = parseFrontmatter( content, source );
	if ( body.includes( '"""' ) ) {
		throw new Error( `${ source }: Codex agent instructions cannot contain a TOML triple-quote sequence.` );
	}
	return `${ TOML_MANAGED_MARKER }\nname = "${ tomlString( name ) }"\ndescription = "${ tomlString( description ) }"\ndeveloper_instructions = """\n${ ensureTrailingNewline( body ) }"""\n`;
}

export async function concatInstructions( instructionsDir ) {
	const names = ( await readdir( instructionsDir ) )
		.filter( ( name ) => name.endsWith( '.md' ) )
		.sort();
	const sections = [];
	for ( const name of names ) {
		const content = ensureTrailingNewline( normalizeMarkdown( await readFile( path.join( instructionsDir, name ), 'utf8' ) ) );
		sections.push( `<!-- source: ${ name } -->\n\n${ content }\n---\n` );
	}
	return `${ sections.join( '\n' ) }\n`;
}

export function concatenatedInstructions( content ) {
	return `${ MANAGED_MARKER }\n${ content }`;
}

export function copilotProjectExport( content ) {
	return `${ COPILOT_EXPORT_MARKER }\n<!-- Do not edit manually. Re-run setup.sh to update. -->\n\n${ content }`;
}
